export const REVEAL_SYNC_BUFFER_MS = 700;
export const REVEAL_FADE_MS = 500;

export const REVEAL_TL = {
  PRE_DELAY: 500,
  GAP_AFTER_1: 1000,
  GAP_AFTER_2: 5000,
  AFTER_3: 2000,
} as const;

export const REVEAL_TOTAL_MS =
  REVEAL_TL.PRE_DELAY + REVEAL_FADE_MS +
  REVEAL_TL.GAP_AFTER_1 + REVEAL_FADE_MS +
  REVEAL_TL.GAP_AFTER_2 + REVEAL_FADE_MS +
  REVEAL_TL.AFTER_3; 