name: deploy-worker
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: pnpm install --frozen-lockfile
      - name: Publish (dev on main / prod on tags)
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            pnpm --filter packages/worker wrangler publish --env dev
          else
            pnpm --filter packages/worker wrangler publish --env prod
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} 